---
- name: Run selected component
  hosts: localhost
  gather_facts: no
  vars:
    component: "{{ component | default('all') }}"

  tasks:

    - name: Run Backend Playbook
      import_playbook: backend.yaml
      when: component == "backend" or component == "all"

    - name: Run Frontend Playbook
      import_playbook: frontend.yaml
      when: component == "frontend" or component == "all"




    