all:
  children:
    frontend:
      hosts:
        frontend.acavinash.fun:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /home/ec2-user/contact-manager-roles/secret/terraform.pem
    backend:
      hosts:
        backend.acavinash.fun:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /home/ec2-user/contact-manager-roles/secret/terraform.pem


# https://github.com/AlankarSingh27/Contact-Manager.git